# ===============================
# DATABASE CONFIG (Neon PostgreSQL)
# ===============================

spring.datasource.url=jdbc:postgresql://ep-bold-base-aif1fsyc-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_oYiHbuBJ02Re

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL (Recommended)
# ===============================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000